# Random Baseline

New object that just does random stuff.

In [6]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
iris = load_iris()
X, y = iris.data, iris.target
y[y != 1] = -1
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [3]:
from sklearn.dummy import DummyClassifier
from sklearn.svm import SVC
clf = SVC(kernel='linear', C=1).fit(X_train, y_train)

print(clf.score(X_test, y_test))

clf = DummyClassifier(strategy='most_frequent', random_state=0)
clf.fit(X_train, y_train)

print(clf.score(X_test, y_test) ) 

0.631578947368421
0.5789473684210527


In [4]:
X_train.shape

(112, 4)

In [8]:
res = np.zeros((10, 1))
res

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [9]:
res.shape

(10, 1)

In [64]:
res[:, 1] = X_train[0:10, 2]

In [62]:
X_train[1:10, 2]

array([4. , 5.5, 1.3, 5.1, 1.6, 1.5, 3.5, 5.5, 5.7])

In [23]:
desc_idx = list(range(3))
desc_idx.remove(1)
desc_idx

[0, 2]

In [51]:
import numpy as np

class VersatileDummy(object):
    """
    Dummy classifier that can take queries.
    """
    def __init__(self):
        self.dummies = []
        return
    
    def fit(self, data, **kwargs):
        
        if isinstance(data, pd.DataFrame):
            data = data.values
        assert isinstance(data,np.ndarray)
        
        nb_rows, nb_atts = data.shape
        
        self.dummies = [DummyClassifier(**kwargs) 
                        for col in range(nb_atts)]
        
        att_idxs = list(range(nb_atts))
        for targ_idx in att_idxs:
            desc_idx = att_idxs.copy().remove(targ_idx)
            
            X = data[:, desc_idx]
            Y = data[:, targ_idx]
            
            self.dummies[targ_idx].fit(X, Y)
            
        return
    
    def predict(self, X, targ_idx):
        return self.dummies[targ_idx].predict(X)

In [54]:
vd = VersatileDummy()
vd.fit(iris.data)

In [58]:
vd.predict(iris.target, 1)

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])