In [1]:
import numpy as np

In [2]:
atts = 10

In [4]:
np.sqrt(16)

4.0

In [6]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [17]:
a = np.eye(10)

In [25]:
np.roll(a, 1, axis=1)

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [27]:
np.zeros_like(a)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [48]:
def init_iteration(nb_atts, nb_targ):
    eye = np.eye(nb_atts)
    res = np.zeros_like(a)
    
    for t in range(nb_targ):
        res += np.roll(eye, t, axis=1)
    
    return res[::nb_targ,]

In [82]:
def change_values(array, old_value, new_value, times):
    
    old_value_idxs = list(np.where(array==old_value)[0])
    shuffle(old_value_idxs)
    
    for t in range(times):
        idx = old_value_idxs.pop()
        array[idx] = new_value
        
    return array

In [91]:
array = np.zeros(10)
array[[1,5,6]]=1
array

array([0., 1., 0., 0., 0., 1., 1., 0., 0., 0.])

In [92]:
change_values(array, 0, -1, 6)

array([-1.,  1., -1., -1., -1.,  1.,  1., -1.,  0., -1.])

In [58]:
indices = np.where(array==0)[0]
indices

array([0, 2, 3, 4, 7, 8, 9])

In [69]:
new = list(indices)

In [73]:
from random import shuffle

In [75]:
shuffle(new)

In [81]:
new.pop()

8

In [35]:
np.where(res[:,-1]

array([0., 0., 0., 0., 0., 0., 0., 0., 1., 1.])

In [16]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])